language: php
php:
  - '5.6'

sudo: false

env:
  matrix:
    - DB=MYSQL CORE_RELEASE=3.4
    - DB=MYSQL CORE_RELEASE=3.5
    - DB=MYSQL CORE_RELEASE=master

matrix:
  allow_failures:
    - env: DB=MYSQL CORE_RELEASE=master

before_script:
  - export COMPOSER_ALLOW_XDEBUG=0
  - phpenv rehash
  - composer self-update || true
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss --require silverstripe/installer
  - cd ~/builds/ss

script:
  - vendor/bin/phpunit faq/tests/
